FROM eclipse-temurin:17 AS GRADLE_BUILD

ENV APP_HOME=/usr/app/
WORKDIR $APP_HOME

COPY . .

run chmod +x gradlew

RUN ./gradle build -x test

FROM debian:latest

RUN apt-get update && apt-get install openjdk-17-jre-headless -y

ENV APP_HOME=/usr/app/

COPY --from=GRADLE_BUILD $APP_HOME/build/libs/PocketFMScrapping-0.0.1-SNAPSHOT.jar /app/

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/PocketFMScrapping-0.0.1-SNAPSHOT.jar"]
