FROM debian:latest AS GRADLE_BUILD

RUN apt-get update && apt-get install openjdk-17-jdk unzip wget -y

RUN wget https://downloads.gradle.org/distributions/gradle-8.3-bin.zip

RUN unzip gradle-8.4-bin.zip -d /opt

ENV GRADLE_HOME /opt/gradle-8.3

ENV PATH "$PATH:/opt/gradle-8.3/bin"

ENV APP_HOME=/usr/app/
WORKDIR $APP_HOME

COPY . .
RUN gradle build -x test

FROM debian:latest

RUN apt-get update && apt-get install openjdk-17-jre-headless -y

ENV APP_HOME=/usr/app/

COPY --from=GRADLE_BUILD $APP_HOME/build/libs/PocketFMScrapping-0.0.1-SNAPSHOT.jar /app/

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/PocketFMScrapping-0.0.1-SNAPSHOT.jar"]
